# GDM configuration storage

[daemon]
# Single-user machine behind LUKS; skip the GDM password prompt.
AutomaticLoginEnable=True
AutomaticLogin=glw907

[security]

[debug]
# Uncomment the line below to turn on debugging
#Enable=true
