#!/bin/sh
# Convert HTML email bodies to clean markdown with clickable terminal links.
#
# Pipeline:
# 1. Strip Mozilla/Thunderbird class attributes that pollute output
# 2. pandoc: HTML -> markdown (unwrap layout tables, strip raw HTML/spans/divs)
# 3. perl: unescape pandoc artifacts, strip images, join multi-line links,
#    normalize whitespace, apply Nord-palette markdown syntax highlighting
# 4. linkify: convert markdown links and bare URLs to OSC 8 clickable links
# 5. colorize: apply ANSI highlighting for quotes, diffs, etc.

echo
sed 's/ class="moz-[^"]*"//g; s/ data-moz-do-not-send="[^"]*"//g; s/ moz-do-not-send="[^"]*"//g' \
    | pandoc -f html \
        -t markdown-raw_html-native_divs-native_spans-header_attributes-bracketed_spans-fenced_divs-inline_code_attributes-link_attributes \
        -L ~/.config/aerc/filters/unwrap-tables.lua \
        --wrap=auto --columns=72 2>/dev/null \
    | perl -CSD -0777 -pe '
        s/\\$//mg;
        s/\\\*/*/g;
        s/\\'"'"'/'"'"'/g;
        s/\[?!\[[^\]]*\]\([^)]*\)\]?(\([^)]*\))?\n?//g;
        s/\[([^\]]*?)\s*\n\s*([^\]]*?)\]\(([^)]*)\)/[$1 $2]($3)/g;
        s/[\x{a0}]+/ /g;
        s/^ +$//mg;
        s/\n{3,}/\n\n/g;
        # Markdown syntax highlighting (Nord palette)
        # Headings: bold blue (#81A1C1)
        s/^(#{1,6})\s+(.*)$/$1 \e[1m\e[38;2;129;161;193m$2\e[0m/mg;
        # Bold: white bold
        s/\*\*(.+?)\*\*/\e[1m$1\e[0m/g;
        # Italic: teal (#8FBCBB)
        s/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/\e[38;2;143;188;187m$1\e[0m/g;
        # Horizontal rules: grey (#616E88)
        s/^-{3,}$/\e[38;2;97;110;136m$&\e[0m/mg;
        s/^_{3,}$/\e[38;2;97;110;136m$&\e[0m/mg;
    ' \
    | linkify \
    | colorize
