#!/usr/bin/env bash
# Scaffold a new .tape file with the determinism defaults this skill preaches
# already baked in, instead of starting from bare `vhs new` (which emits a
# tape with none of them) and reconstructing the same Set block from memory
# every time.
#
# Usage:
#   new_tape.sh <name> [--gif|--still] [--force]
#
#   <name>     Base name, without extension (e.g. "demo-history").
#   --gif      Motion capture: emits `Output <name>.gif` (default).
#   --still    Single-frame capture: emits `Screenshot <name>.png`.
#   --force    Overwrite <name>.tape if it already exists.
#
# Writes ./<name>.tape. Fill in the TODO markers: the command to launch, the
# fixture setup inside Hide/Show, and the keystrokes/sleeps for the scene.

set -euo pipefail

mode="gif"
force="false"
name=""

for arg in "$@"; do
  case "$arg" in
    --gif) mode="gif" ;;
    --still) mode="still" ;;
    --force) force="true" ;;
    -h|--help)
      echo "usage: new_tape.sh <name> [--gif|--still] [--force]" >&2
      exit 0
      ;;
    -*)
      echo "unknown flag: $arg" >&2
      exit 2
      ;;
    *)
      name="$arg"
      ;;
  esac
done

if [ -z "$name" ]; then
  echo "usage: new_tape.sh <name> [--gif|--still] [--force]" >&2
  exit 2
fi

tape="${name}.tape"

if [ -f "$tape" ] && [ "$force" != "true" ]; then
  echo "· $tape already exists — pass --force to overwrite" >&2
  exit 1
fi

# `Output` is declarative — it can sit near the top and just names where the
# whole session gets recorded. `Screenshot` is NOT declarative — it captures a
# single frame at the exact point it appears, so it belongs at the end of the
# scene (once the app has reached the state worth capturing), never up front.
if [ "$mode" = "gif" ]; then
  output_line="Output ${name}.gif    # motion capture — declarative, records the whole session"
  settle_comment="# shorter settle than a still — loading frames read as natural startup"
  settle_sleep="Sleep 1500ms"
  closing_comment="# TODO: drive the scene — Type/Key + Sleep to hold each beat long
# enough to read (~2.5s after text, ~1.2s on a view switch, ~0.5s between
# quick keystrokes). End on the UI — no trailing quit on camera."
else
  output_line="# (no Output line for a still — see the Screenshot line at the end of the scene)"
  settle_comment="# generous settle: this is a still, there's no second chance at a frame"
  settle_sleep="Sleep 5s"
  closing_comment="# TODO: drive to the state you want to capture (Type/Key), hold briefly,
# then capture it — Screenshot must come here, AFTER the app has reached the
# state you want, not up front:
Screenshot ${name}.png"
fi

cat > "$tape" <<TAPE
# ${name}.tape
# Generated by vhs-cli-demos/scripts/new_tape.sh — fill in the TODOs below.
# Render with: vhs ${tape}

# --- determinism + framing ---
Set Shell "bash"
Set FontSize 20          # readable; canvas left to VHS defaults so it stays
                         # sharp when a README/docs page scales it up
Set Padding 24
Set Theme "Catppuccin Mocha"   # lock the theme — don't rely on ambient terminal colours
Set CursorBlink false
Set TypingSpeed 50ms
# No Set Width/Height — see references/tape-reference.md if you genuinely
# need a fixed canvas across a set of captures (keep it generous).

${output_line}

# --- hidden setup (not recorded) ---
Hide
# TODO: unquoted \$PATH so it actually expands, e.g.:
#   Type "export PATH=/repo/node_modules/.bin:\$PATH" Enter
# TODO: pin "now" if the app renders relative dates, e.g.:
#   Type "export MYAPP_NOW=2024-01-15T12:00:00Z" Enter
# TODO: cd into a deterministic fixture (see recipe-catalog-pattern.md for
# the git-scenarios package if this app operates on a git repo), then:
Type "clear" Enter
Show

# --- the scene ---
# TODO: launch the app
Type "myapp" Enter
${settle_comment}
${settle_sleep}

${closing_comment}
TAPE

echo "· wrote $tape ($mode) — fill in the TODOs, then: vhs $tape"
