[907.life]
source = jmap://geoff@907.life@api.fastmail.com
outgoing = jmap://
default = INBOX
from = Geoff Wright <geoff@907.life>
source-cred-cmd = op read "op://Private/Fastmail/Saved on app.fastmail.com/workstation jmap token"
