[907.life]
source = jmap+oauthbearer://api.fastmail.com/jmap/session
outgoing = jmap://
default = INBOX
from = Geoff Wright <geoff@907.life>
source-cred-cmd = fastmail-password
folders = Inbox,Drafts,Sent,Archive,Notifications,Buccaneer 18,Remind,Spam,Trash
folders-sort = Inbox,Drafts,Sent,Archive,Notifications,Buccaneer 18,Remind,Spam,Trash
