[907.life]
source = jmap+oauthbearer://api.fastmail.com/jmap/session
outgoing = jmap://
default = INBOX
from = Geoff Wright <geoff@907.life>
reply-to-self = false
source-cred-cmd = fastmail-password
folders = Inbox,Drafts,Sent,Archive,Finance Committee,Membership Committee,Program Committee,Buccaneer 18,Notifications,Remind,Spam,Trash
folders-sort = Inbox,Drafts,Sent,Archive,Notifications,Program Committee,Membership Committee,Finance Committee,Buccaneer 18,Remind,Spam,Trash
cache-state = true
cache-blobs = true
